---
title: "Kids, Cops, and Community"
subtitle: "A qualitative assessment of police-community relations in Aurora, CO"
---

# Background  

The City of Aurora, Colorado and the Aurora Police Department engaged Colorado School of Public Health researchers in 2011 to support their planning efforts to design and implement gang and youth violence intervention and prevention programming under the Aurora for Youth program. The School continued its involvement in this programming through 2018, helping to evaluate the impact of 
the grant-funded Violence Prevention program, ViP, and city-funded Aurora's Gang Reduction Impact Program (A-GRIP). A sub-project of these efforts, the Kids, Cops, and Community (KCC), was funded to support Aurora for Youth's planning and evaluation efforts. KCC had two aims:  

1. Explore the current state of relations between kids of color and their parents and police in order to better understand the possible existence and extent of tensions between community and police.  
2. Design an evaluation mechanism to descrive the impact of A-GRIP on reducing youth recidivism rates in the target area.  

Nicole oversaw all activities on this project, directing the work of two staff and executing tasks herself.  


# Timeline 

October 2017 - September 2018 

# Main Activities  

* Facilitate monthly working group meetings with community members, community organization representatives, and criminal justice system representatives  
* Aim 1: tensions between police and youth
  + Conduct interviews and focus groups with youth, parents, and police officers  
  + Conduct a literature review of best practices in resolving tensions between police and communities of color 
  + Summarize findings into list of recommendations for police department and community  
* Aim 2: evaluation plan  
  + Create a logic model, goals, and objectives for A-GRIP's programming  
  + Design a procedure to collect data and assess relationship between case management services and recidivism rate  


# Tools Created  
  
* Interview guide  
* Focus group script  
* Logic Model

# Results   

Making Logic Out of Stakeholder Engagement: Developing the Basis for an Evaluation Plan  
Kids, Cops, and Community: A Qualitative Assessment of Police, Youth, and Parent Perceptions of Each Other  