project:
  type: website
  resources: 
    - "*.pdf"
    - "Projects/*.pdf"

website:
  title: "Nicole Harty, MPH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pubs_reports.qmd
      - projects.qmd
      - skills.qmd  
    right:
      - href: https://docs.google.com/document/d/1S2ETgy2U0OXTqqKKPpCdZNsVKK9-nYxwhbq7yEpxjrM/edit
        text: "{{< fa regular file >}} Resume"
      
        
  page-footer: 
    left: "{{< fa regular copyright >}} Nicole Harty, 2024. Made with [Quarto](https://quarto.org)."
  link-external-newwindow:

execute: 
  freeze: auto

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



